server:
  port: 2101
spring:
  application:
    name: test-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luotongluo/TestSpring/feature-lt-0408
          search-paths: spring-config
          username: 1282875540@qq.com
          password: luo1234tong
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/